#!/bin/sh

# Copyright (c) 2013-2015, CZ.NIC, z.s.p.o. (http://www.nic.cz/)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the CZ.NIC nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL CZ.NIC BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

PARTITION=/dev/mtdblock4
WORKDIR=/tmp/certstore
SUBVOL=certbackup

mkdir -p "$(dirname "$WORKDIR")"
mkdir "$WORKDIR"
trap "umount -fl '$WORKDIR' || true; rmdir '$WORKDIR' || true" EXIT INT QUIT TERM ABRT

test -z "$(ls -A "$WORKDIR")"
if test -b "$PARTITION"; then
	mount -t jffs2 -o compr=none "$PARTITION" "$WORKDIR"
else
	if grep -q '/dev/mmcblk0p1 / btrfs' /proc/mounts && \
	   ! btrfs subvol list / | grep -q "path $SUBVOL"; then
		mount -t btrfs -o subvol=/ /dev/mmcblk0p1 "$WORKDIR"
		btrfs subvolume create "$WORKDIR"/"$SUBVOL"
		umount "$WORKDIR"
	fi
	mount -t btrfs -o subvol=/"$SUBVOL" /dev/mmcblk0p1 "$WORKDIR"
fi
while [ "$1" ] ; do
	if [ "$1" = '-r' ] ; then
		# It should be removed, if it exists
		shift
		rm -f "$WORKDIR"/"$1"
	elif [ "$1" = '-x' ] ; then
		# Reverse, extractor mode
		shift
		cp -a "$WORKDIR"/"$1" "$1"
	elif [ "$1" = '-X' ] ; then
		# Reverse, all extractor mode somewhere
		DEST="/"
		if [ -n "$2" ]; then
			DEST="$2"
			shift
		fi
		[ -z "$(ls -1 "$WORKDIR")" ] || cp -ra "$WORKDIR"/* "$DEST"
	elif cmp -s "$1" "$WORKDIR"/"$1" ; then
		echo "$1" already stored, skipping
	else
		# It differs (or the backup doesn't exist) -> replace
		mkdir -p "$WORKDIR"/"$(dirname "$1")"
		cp -a "$1" "$WORKDIR"/"$1"
	fi
	shift
done
