#!/bin/sh

# The first line of the remote command should be the directory to store to
read DIRECTORY
cd "$DIRECTORY"
DATE="$(date +%Y-%m-%d-%H-%M)"
NAME="$DATE".dbdump.xz.gpg
touch "$NAME"
chmod 0600 "$NAME"
cat >"$NAME"
chmod 0400 "$NAME"
