#!/bin/sh

set -e

DIR="/tmp/crldown.$$"

# The time of 4 hours should be enough for the CRL not to time out. Hopefuly.
if [ -f /tmp/crl.pem ] && [ "$((`date +%s`-4*3600))" -lt "$((`date -r /tmp/crl.pem +%s`))" ] ; then
	exit
fi

mkdir "$DIR"
trap 'rm -rf "$DIR"' EXIT ABRT QUIT TERM INT
cd "$DIR"

set +e
# We download through https mostly out of habit. But we could
# as securely use http, since the CRL is cryptographically signed
# and can't be forged.
curl -k https://api.turris.cz/crl -o "$DIR/crl.pem" && mv "$DIR/crl.pem" /tmp/crl.pem
# Even if it fails, we want to return success. That way, any possible previous
# version of the CRL may still be used unless it expired.
# The only case when we want to return failure is when the file /tmp/crl.pem doesn't exist.
[ -f /tmp/crl.pem ]
