#!/bin/sh

echo "TODO: Add alternative names, as they are now preferred over CN"

set -ex
cd $(dirname "$0")
openssl genrsa -out new.key 4096
openssl req -new -key new.key -out new.csr
openssl ca -batch -config config -notext -in new.csr -out new.crt
