#!/bin/sh

base_dir=/tmp/user_notify

usage() {
	echo "This program serves for creating messages which will be send to the user."
	echo "Usage:"
	echo -e "\t $0 -s [restart,error,upate,news] 'text of the message'"
}

trigger=false

if [ $1 = -t ] ; then
	trigger=true
	shift
fi

if [ $1 = -d ] ; then
	base_dir="$2"
	shift 2
fi

if [ $# -ne 3 ]; then
	usage
	exit 1
fi

if [ $1 = "-s" ]; then
	if [ $2 = "restart" ] || [ $2 = "error" ] || [ $2 = "update" ] || [ $2 = "news" ]; then
		severity=$2
	else
		usage
		exit 1
	fi
else
	usage
	exit 1
fi

message=$3
# This should be unique
msg_id=$(date +%s)-$$

mkdir -p $base_dir
mkdir $base_dir/tmp.$msg_id
echo $severity > $base_dir/tmp.$msg_id/severity
echo $message > $base_dir/tmp.$msg_id/message

mv $base_dir/tmp.$msg_id $base_dir/$msg_id

if $trigger ; then
	exec notifier -d "$base_dir"
fi
