#!modules/module.sh

help="
gather dns related informations
"

run () {
	# resolver config
	uci -q show resolver
	echo

	# root key
	ls -al /etc/root.keys
	md5sum /etc/root.keys
	ls -al /etc/unbound/root.key
	md5sum /etc/unbound/root.key
	echo

	grep -H '' /etc/resolv.conf*

	# try to resolve some server
	nslookup api.turris.cz 127.0.0.1  # should pass
	nslookup www.rhybar.cz 127.0.0.1  # should fail
	nslookup *.wilda.rhybar.0skar.cz 127.0.0.1  # should fail
	nslookup *.wilda.nsec.0skar.cz 127.0.0.1  # should pass
	nslookup *.wild.nsec.0skar.cz 127.0.0.1  # should pass
	nslookup *.wilda.0skar.cz 127.0.0.1  # should pass
	nslookup *.wild.0skar.cz 127.0.0.1  # should pass
	nslookup www.wilda.nsec.0skar.cz 127.0.0.1  # should pass
	nslookup www.wilda.0skar.cz 127.0.0.1  # should pass
	nslookup *.wilda.rhybar.ecdsa.0skar.cz 127.0.0.1  # should fail
}
