#!modules/module.sh

help="
gather dns related informations
"

run () {
	# resolver config
	uci -q show resolver
	echo

	echo "== resolv.conf* =="
	grep -H '' /etc/resolv.conf* /tmp/resolv.conf*

	echo "== DNSSEC root key file =="
	ROOTKEYFILE=$(uci get resolver.common.keyfile)
	ls -al "${ROOTKEYFILE}"
	md5sum "${ROOTKEYFILE}"
	grep -H '' "${ROOTKEYFILE}"
	echo

	echo "== resolver process =="
	RESOLVER="$(uci get resolver.common.prefered_resolver)"
	ps w | grep ${RESOLVER}

	# try to resolve some server
	nslookup api.turris.cz 127.0.0.1  # should pass
	nslookup www.rhybar.cz 127.0.0.1  # should fail
	nslookup *.wilda.rhybar.0skar.cz 127.0.0.1  # should fail
	nslookup *.wilda.nsec.0skar.cz 127.0.0.1  # should pass
	nslookup *.wild.nsec.0skar.cz 127.0.0.1  # should pass
	nslookup *.wilda.0skar.cz 127.0.0.1  # should pass
	nslookup *.wild.0skar.cz 127.0.0.1  # should pass
	nslookup www.wilda.nsec.0skar.cz 127.0.0.1  # should pass
	nslookup www.wilda.0skar.cz 127.0.0.1  # should pass
	nslookup *.wilda.rhybar.ecdsa.0skar.cz 127.0.0.1  # should fail
}
